---
title: "Assignment Exercise 10-13"
author: "Alex"
date: "26/09/2019"
output:
  pdf_document: default
  html_document: default
---
##Chapter 10 Exercise 10.1
```{r}
# Question a
Vec1 <- c(2,1,1,3,2,1,0)
Vec2 <- c(3,8,2,2,0,0,0)

#i
if((Vec1[1]+Vec2[2])==10){cat("Print me!")} # It meets the condition and Prints
#ii
if(Vec1[1]>=2&&Vec2[1]>=2){ cat("Print me!")}# It meets the condition and Prints
#iii
if(all((Vec2-Vec1)[c(2,6)]<7)){ cat("Print me!")}# Didn't meet the condition
#iv
if(!is.na(Vec2[3])){ cat("Print me!") } # It meets the condition and Prints

# Question b
result<- ifelse(Vec1+Vec2>3,yes=Vec1*Vec2,no=Vec1+Vec2)
result
# Question c
new2mat<- matrix(as.character(),2,2)
if(any(toupper(substr(diag(new2mat)),1,1)=="g")||any(tolower(substr(diag(new2mat)),1,1)=="G")){
  Ent <- which(toupper(substr(diag(new2mat),1,1)=="g"|substr(diag(new2mat),1,1)=="G"))
  diag(new2mat)[Ent] <- "HERE"
} else {
  new2mat <- diag(nrow(new2mat))
}
new2mat
# i
mymat <- matrix(as.character(1:16),4,4)
mymat
# ii
mymat <- matrix(c("DANDELION","Hyacinthus","Gerbera","MARIGOLD","geranium","ligularia","Pachysandra","SNAPDRAGON","GLADIOLUS"),3,3)
mymat
# iii
mymat <- matrix(c("GREAT","exercises","right","here"),2,2,byrow=T)
mymat
#Exercise 10.2 

mynum <- 3
mynum <- 0
# Question a
if(mynum==1){
  foo <- 12
} else if(mynum==2){
  foo <- 34
} else if(mynum==3){
  foo <- 56
} else if(mynum==4){
  foo <- 78
} else if(mynum==5){
  foo <- NA
} else {
  foo <- NULL
}
foo
# Question b
doselevel <- factor(c("Low","Med","High"),levels=c("Low","Med","High"))
lowdose<- 0
meddose<- 0
highdose<- 0
if(any(doselevel=="High")){
  if(lowdose>=10){
    lowdose <- 10
  } else {
    lowdose <- lowdose/2
  }
  if(meddose>=26){
    meddose <- 26
  }
  if(highdose<60){
    highdose <- 60
  } else {
    highdose <- highdose*1.5
  }
  dosage <- rep(lowdose,length(doselevel))
  dosage[doselevel=="Med"] <- meddose
  dosage[doselevel=="High"] <- highdose
} else {
  doselevel <- factor(doselevel,levels=c("Low","Med"),labels=c("Small","Large"))
  if(lowdose<15 && meddose<35){
    lowdose <- lowdose*2
    meddose <- meddose+highdose
  }
  dosage <- rep(lowdose,length(doselevel))
  dosage[doselevel=="Large"] <- meddose
}
# i
lowdose <- 12.5
meddose <- 25.3
highdose <- 58.1
doselevel <- factor(c("Low","High","High","High","Low","Med","Med"),levels=c("Low","Med","High"))
# ii
lowdose <- 12.5
meddose <- 25.3
highdose <- 58.1
doselevel <- factor(c("Low","Low","Low","Med","Low","Med","Med"),levels=c("Low","Med","High"))
# iii
lowdose <- 9
meddose <- 49
highdose <- 61
doselevel <- factor(c("Low","Med","Med"),levels=c("Low","Med","High"))
# iv
lowdose <- 9
meddose <- 49
highdose <- 61
doselevel <- factor(c("Low","High","High","High","Low","Med","Med"),levels=c("Low","Med","High"))
# Question c
mynum <- 3
ifelse(mynum>0,switch(mynum,"one","two","three","four","five","six","seven","eight","nine"),"zero")
mynum <- 0
ifelse(mynum>0,switch(mynum,"one","two","three","four","five","six","seven","eight","nine"),"zero")

# Exercise 10.3 
# Question a
loopvec1 <- 5:7
loopvec2 <- 9:6
foo <- matrix(NA,length(loopvec1),length(loopvec2))
for(i in 1:length(loopvec1)){
  foo[i,] <- loopvec1[i]*loopvec2
}
foo
# Question b
mystring <- c("Peter","Homer","Lois","Stewie","Maggie","Bart")
mynums <- rep(NA,length(mystring))
for(i in 1:length(mystring)){
  mynums[i] <- switch(EXPR=mystring[i],Homer=12,Marge=34,Bart=56,Lisa=78,Maggie=90,NA)
}
# Question c
counter <- 0
for(i in 1:length(mylist)){
  member <- mylist[[i]]
  if(is.matrix(member)){
    counter <- counter+1
  } else if(is.list(member)){
    for(j in 1:length(member)){
      if(is.matrix(member[[j]])){
        counter <- counter+1
      }
    }
  }
}
# i
mylist <- list(aa=c(3.4,1),bb=matrix(1:4,2,2),cc=matrix(c(T,T,F,T,F,F),3,2),dd="string here",ee=list(c("hello","you"),matrix(c("hello","there"))),ff=matrix(c("red","green","blue","yellow")))
# ii
mylist <- list("tricked you",as.vector(matrix(1:6,3,2)))
# iii
mylist <- list(list(1,2,3),list(c(3,2),2),list(c(1,2),matrix(c(1,2))),rbind(1:10,100:91))

# 10.4 
# Question a
# i
mylist <- list()
counter <- 1
mynumbers <- c(2,2,2,2,5,2)
mycondition <- mynumbers[counter]<=5
mycondition
while(mycondition){
  mylist[[counter]] <- diag(mynumbers[counter])
  counter <- counter+1
  if(counter<=length(mynumbers)){
    mycondition <- mynumbers[counter]<=5
  } else {
    mycondition <- FALSE
  }
}
mylist
# ii
mylist <- list()
counter <- 1
mynumbers <- 2:20
mycondition <- mynumbers[counter]<=5
mycondition
while(mycondition){
  mylist[[counter]] <- diag(mynumbers[counter])
  counter <- counter+1
  if(counter<=length(mynumbers)){
    mycondition <- mynumbers[counter]<=5
  } else {
    mycondition <- FALSE
  }
}
mylist
# iii 
mylist <- list()
counter <- 1
mynumbers <- c(10,1,10,1,2)
mycondition <- mynumbers[counter]<=5
mycondition
while(mycondition){
  mylist[[counter]] <- diag(mynumbers[counter])
  counter <- counter+1
  if(counter<=length(mynumbers)){
    mycondition <- mynumbers[counter]<=5
  } else {
    mycondition <- FALSE
  }
}
mylist
# Question b
mynewnum <- 1
while(mynum>1){
  mynewnum <- mynewnum*mynum
  mynum <- mynum-1
}
mynewnum
# i
mynum <- 5
mynewnum <- 1
while(mynum>1){
  mynewnum <- mynewnum*mynum
  mynum <- mynum-1
}
mynewnum
# ii
mynum <- 12
mynewnum <- 1
while(mynum>1){
  mynewnum <- mynewnum*mynum
  mynum <- mynum-1
}
mynewnum
# iii
mynum <- 0
mynewnum <- 1
while(mynum>1){
  mynewnum <- mynewnum*mynum
  mynum <- mynum-1
}
mynewnum
# Question c
mystring <- "R fever"
mystring <- "beautiful"
mystring <- "ECCENTRIC"
mystring <- "ElAbOrAte"
mystring <- "eeeeek!"
#--#
index <- 1
ecount <- 0
result <- mystring
while(ecount<2 && index<=nchar(mystring)){
  temp.char <- substr(mystring,index,index)	
  if(temp.char=="e"||temp.char=="E"){
    ecount <- ecount+1
  }
  if(ecount==2){
    result <- substr(mystring,1,index-1)
  }
  index <- index + 1
}
result

# Exercise  10.5 
# Question a
foo <- matrix(1:12,4,3)
apply(apply(foo,1,sort,decreasing=TRUE),2,prod)
foo
# Question b
matlist <- list(matrix(c(T,F,T,T),2,2),
                matrix(c("a","c","b","z","p","q"),3,2),
                matrix(1:8,2,4))
matlist
for(i in 1:length(matlist)){
  matlist[[i]] <- t(matlist[[i]])
}
matlist
matlist <- list(matrix(c(T,F,T,T),2,2),matrix(c("a","c","b","z","p","q"),3,2),matrix(1:8,2,4))
matlist
matlist <- lapply(matlist,t)
matlist
# Question c
qux <- array(96:1,dim=c(4,4,2,3))
# i
apply(qux[,,2,],3,diag)
# ii
apply(apply(qux[,4,,],3,dim),1,sum)

# Exerise 10.6 
# Question a
foo <- 5
bar <- c(2,3,1.1,4,0,4.1,3)
# i
loop2.result <- rep(NA,length(bar))
condition <- TRUE
count <- 1
while(condition){
  temp <- foo/bar[count]
  if(is.finite(temp)){
    loop2.result[count] <- temp
  } else {
    condition <- FALSE
  }
  count <- count+1
}
loop2.result
# ii
loop3.result <- ifelse(is.finite(foo/bar),foo/bar,NA)
loop3.result
# Question b
mynumbers <- c(4,5,1,2,6,2,4,6,6,2)
# i
mylist <- list()
for(i in 1:length(mynumbers)){
  if(mynumbers[i]<=5){
    mylist[[i]] <- diag(mynumbers[i])
  } else {
    break
  }
}
mylist
# ii
mylist <- list()
counter <- 0
repeat{
  counter <- counter+1
  if(counter<=length(mynumbers)){
    if(mynumbers[counter]<=5){
      mylist[[counter]] <- diag(mynumbers[counter])
    } else {
      break
    }
  } else {
    break
  }
}
mylist
# Question c
counter <- 0
reslist <- list()
for(i in 1:length(matlist1)){
  for(j in 1:length(matlist2)){
    counter <- counter+1
    if(ncol(matlist1[[i]])!=nrow(matlist2[[j]])){
      reslist[[counter]] <- "not possible"
      next
    }
    reslist[[counter]] <- matlist1[[i]]%*%matlist2[[j]]
  }
}
reslist
# (i)
matlist1 <- list(matrix(1:4,2,2),matrix(1:4),matrix(1:8,4,2))
matlist2 <- matlist1
# ii
matlist1 <- list(matrix(1:4,2,2),matrix(2:5,2,2),matrix(1:16,4,2))
matlist2 <- list(matrix(1:8,2,4),matrix(10:7,2,2),matrix(9:2,4,2))

```

## Chapter 11 Exerise 11

```{r}
# Exercise 11.1
# Question a
myfib4 <- function(thresh,printme){
  if(printme){
    fibA <- 1
    fibB <- 1
    cat(fibA,", ",fibB,", ",sep="")
    repeat{
      result <- fibA + fibB
      fibA <- fibB
      fibB <- result
      cat(fibB,", ",sep="")
      if(fib.B>thresh){
        cat("BREAK NOW...")
        break
      }
    }
  } else {
    fibseq <- c(1,1)
    counter <- 2
    repeat{
      fibseq <- c(fibseq,fibseq[counter-1]+fibseq[counter])
      counter <- counter+1
      if(fibseq[counter]>thresh){
        break
      }
    }
    return(fibseq)
  }
}
myfib4(thresh=150,printme=TRUE)
myfib4(1000000,T)
myfib4(150,FALSE)
myfib4(1000000,printme=F)
# Question b
# i
myfac <- function(int){
  Funcres <- 1
  while(int>1){
   Funcres <- Funcres*int
    int <- int-1
  }
  return(Funcres)
}
myfac(5)
myfac(12)
myfac(0)
# ii
myfac2 <- function(int){
  if(int<0){
    return(NaN)
  }
 Funcres <- 1
  while(int>1){
    Funcres <- Funcres * int
    int <- int-1
  }
  return(Funcres)
}
myfac2(5)
myfac2(12)
myfac2(0)
myfac2(-6)

# Exercise 11.2
# Question a
comp <- function(P,i,t=12,y,plotit=TRUE,...){
  yseq <- 1:y
  values <- P*(1+i/(100*t))^(t*yseq)
  
  if(plotit){  
    plot(yseq,values,type="s",...)
  } else {
    return(values)
  }
}
# i
compd(5000,4.4,y=10,plotit=F)[10]
# ii
compd(100,22.9,12,20,plotit=T,main="Compound interest calculator",ylab="Balance (F)",xlab="Year (y)")
# iii
ann <- compd(100,22.9,1,20,plotit=F)
lines(1:20,ann,lty=2,type="s")
legend("topleft",lty=c(1,2),legend=c("monthly interest","annual interest"))
# Question b
quad <- function(k1,k2,k3){
  if(any(c(missing(k1),missing(k2),missing(k3)))){
    return("At least one of k1, k2, k3 was missing")
  }
  x <- k2^2-4*k1*k3
  if(x<0){
    cat("No real roots\n")
  } else if(x==0){
    return(-k2/(2*k1))
  } else {
    return(c((-k2-x^0.5)/(2*k1),(-k2+x^0.5)/(2*k1)))
  }
}
# i
quad(k1=2,k2=-1,k3=-5)
quad(1,1,1)
# ii
quad(k1=1.3,k2=-8,k3=-3.13)
quad(2.25,-3,1)
quad(1.4,-2.2,-5.1)
quad(-5,10.11,-9.9)
# iii
quad(0)

# Exercise 11.3
# Question a
foo <- list("a",c("b","c","d","e"),"f",c("g","h","i"))
lapply(foo,function(x) paste(x,"!",sep=""))
# Question b
Rec <- function(x){
  if(x==0){
    return(1)
  } else {
    return(x*Rec(x-1))
  }
}
# i
Rec(5)
# ii
Rec(12)
# iii
Rec(0)
# Question c
geolist <- function(x){
  FuncGeo <- function(nums){
    return(prod(nums)^(1/length(nums)))
  }
  
  for(i in 1:length(x)){
    if(!is.matrix(x[[i]])){
      x[[i]] <- FuncGeo(x[[i]])
    } else {
      x[[i]] <- apply(x[[i]],1,FuncGeo)
    }
  }
  return(x)
}
# i
foo <- list(1:3,matrix(c(3.3,3.2,2.8,2.1,4.6,4.5,3.1,9.4),4,2),matrix(c(3.3,3.2,2.8,2.1,4.6,4.5,3.1,9.4),2,4))
geolist(foo)
# ii
bar <- list(1:9,matrix(1:9,1,9),matrix(1:9,9,1),matrix(1:9,3,3))
geolist(bar)

```

## Chapter 12 Exercise 12

```{r }
# Exercise 12.1
# Question a
facrec2 <- function(x){
  if(x<0){
    stop("'x' must be a positive integer")
  }
  
  if(x==0){
    return(1)
  } else {
    return(x*facrec2(x-1))
  }
}
# i
facrec2(5)
# ii
facrec2(8)
# iii
facrec2(-8)
# Question b
matinv <- function(x,noninv=NA,nonmat="not a matrix",silent=TRUE){
  if(!is.list(x)){
    stop("'x' must be a list")
  }
  
  n <- length(x)
  if(n==0){
    stop("'x' appears to be empty")
  }
  
  if(!is.character(nonmat)){
    warning("attempting to coerce 'nonmat' to a character string")
    nonmat <- as.character(nonmat)
  }
  
  for(i in 1:n){
    if(is.matrix(x[[i]])){
      attempt <- try(solve(x[[i]]),silent=silent)
      if(class(attempt)=="try-error"){
        x[[i]] <- noninv
      } else {
        x[[i]] <- attempt
      }
    } else {
      x[[i]] <- nonmat
    }
  }
  
  return(x)
}
# i
x <- list(1:4,matrix(1:4,1,4),matrix(1:4,4,1),matrix(1:4,2,2))
matinv(x)
# ii
matinv(x,noninv=Inf,nonmat=666)
# iii
matinv(x,noninv=Inf,nonmat=666,silent=F)
# iv
x <- list(diag(9),matrix(c(0.2,0.4,0.2,0.1,0.1,0.2),3,3),rbind(c(5,5,1,2),c(2,2,1,8),c(6,1,5,5),c(1,0,2,0)),matrix(1:6,2,3),cbind(c(3,5),c(6,5)),as.vector(diag(2)))
matinv(x,noninv="unsuitable matrix")
# v
x <- "hello"
matinv(x)
# vi
x <- list()
matinv(x)

# Exercise 12.2
# Question a
prog_test_fancy <- function(n,...){
  result <- 0
  progbar <- txtProgressBar(min=0,max=n,...)
  for(i in 1:n){
    result <- result + 1
    Sys.sleep(0.5)
    setTxtProgressBar(progbar,value=i)
  }
  close(progbar)
  return(result)
}
ence <- Sys.time()
prog_test_fancy(50,style=3,char="r")
differ <- Sys.time()
differ-ence
# Question b
myfibrec2 <- function(n){
  if(n<0){
    warning("Assuming you meant 'n' to be positive -- doing that instead")
    n <- n*-1
  } else if(n==0){
    stop("'n' is uninterpretable at 0")
  }
  
  if(n==1||n==2){
    return(1)
  } else {
    return(myfibrec2(n-1)+myfibrec2(n-2))
  }
}
myfibvectorTRY2 <- function(nvec){
  nterms <- length(nvec)
  result <- rep(0,nterms)
  progbar <- txtProgressBar(min=0,max=nterms,style=3,char="-")
  for(i in 1:nterms){
    attempt <- try(myfibrec2(nvec[i]),silent=T)
    if(class(attempt)=="try-error"){
      result[i] <- NA
    } else {
      result[i] <- attempt
    }
    setTxtProgressBar(progbar,value=i)
  }
  close(progbar)
  return(result)
}
# i
myfibvectorTRY2(nvec=c(3,2,7,0,9,13))
# ii
t1 <- Sys.time()
myfibvectorTRY2(1:35)
t2 <- Sys.time()
t2-t1

# Question c
t1 <- Sys.time()
fibvec <- c(1,1,rep(NA,33)) 
for(i in 3:35){
  fibvec[i] <- fibvec[i-2]+fibvec[i-1]
}
fibvec
t2 <- Sys.time()
t2-t1
```

## Chapter 13 Exercise 13
```{r}
# Exercise 13.1 
# Question a
# i numeric-discrete
# ii categorical-ordinal
# iii numeric-continuous
# iv categorical-ordinal
# v categorical-nominal
# vi numeric-continuous

# Question b
# i Sample statistic. Population parameter here describes the proportion of NZers who own a gaming console.
# ii Sample statistic. Population parameter here describes the average number of blemishes on the hoods of all cars at No Dodgy Carz yard.
# iii Population parameter.
# iv Population parameter.
# v Sample statistic. Population parameter here describes average number of times per day a vending machine is used in a year

## Exercise 13.2
# Question a
round(mean(quakes$depth>=300),2)
# Question b
mean(quakes$mag[quakes$depth>=300])
median(quakes$mag[quakes$depth>=300])
# Question c
for(i in levels(chickwts$feed)){
  cat(i,": ",round(mean(chickwts$weight[chickwts$feed==i]),1)," grams\n",sep="")
}
# Question d 
#The two variables types in InsectSprays are count: numeric-discrete; spray: categorical-nominal
# Question e
Ctab <- table(InsectSprays$count)
Ctab[Ctab==max(Ctab)]
# Question f
tapply(InsectSprays$count,INDEX=InsectSprays$spray,FUN=sum)
# Question g
for(i in levels(InsectSprays$spray)){
  cat("Spray ",i,"; at least 5 bugs: ",round(mean(InsectSprays$count[InsectSprays$spray==i]>=5)*100,0),"% \n",sep="")
}
# Question h
tapply(InsectSprays$count,INDEX=InsectSprays$spray,FUN=function(x) round(mean(x>=5)*100,0))

## Exercise 13.3 

# Question a
quantile(chickwts$weight,c(0.1,0.3,0.9))
chickvars <- tapply(chickwts$weight,INDEX=chickwts$feed,FUN=var)
chickvars[chickvars==max(chickvars)]
# Question b
# i
IQR(quakes$depth)
# ii
summary(quakes$mag[quakes$depth>=400]) ### Magnitudes at <400 have a similar amount of spread as those at >=400 (and an equivalent IQR of 0.5), but are centered at slightly higher values.
# iii
dmin <- min(quakes$depth)
dmax <- max(quakes$depth)
depthcat <- cut(quakes$depth,breaks=seq(dmin,dmax,length=5),include.lowest=TRUE,right=FALSE)
levels(depthcat)
# iv
tapply(quakes$mag,INDEX=depthcat,FUN=mean)
tapply(quakes$mag,INDEX=depthcat,FUN=sd)
# v
tapply(quakes$mag,INDEX=depthcat,FUN=quantile,prob=0.8)


## Exercise 13.4
# Question a
w <- c(55,85,75,42,93,63,58,75,89,67)
h <- c(161,185,174,154,188,178,170,167,181,178)
cor(w,h)
# Question b
# i
mtcars
?mtcars
# ii )
plot(mtcars$hp,mtcars$qsec,xlab="horsepower",ylab="1/4 mile time")
cor(mtcars$hp,mtcars$qsec)
# iii
tran <- factor(mtcars$am,labels=c("auto","manual"))
# iv
library(ggplot2)
qplot(mtcars$hp,mtcars$qsec,col=tran,xlab="horsepower",ylab="1/4 mile time")
# v
cor(mtcars$hp[tran=="manual"],mtcars$qsec[tran=="manual"])
cor(mtcars$hp[tran=="auto"],mtcars$qsec[tran=="auto"]) 
# Separated by transmission type, correlations are more extreme than when pooled. Manual cars have a slightly more extreme negative correlation between the two variables than automatic cars.
# Question c
# i
sunchicks <- chickwts$weight[chickwts$feed=="sunflower"]
plot(sunchicks,rep(0,length(sunchicks)),yaxt="n",bty="n",xlab="sunflower chick weights",ylab="")
abline(h=0,col="gray",lty=2)
# ii
sd(sunchicks)
IQR(sunchicks)
# iii
sd(sunchicks[-which(sunchicks==min(sunchicks))])
IQR(sunchicks[-which(sunchicks==min(sunchicks))]) 
# Both measures of spread decrease with the deletion of the lowest weight; though the sd is affected more than the IQR...

```

